# Generated by Django 5.0.4 on 2024-05-30 03:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Mysite', '0005_rename_product_name_product_name_cart_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart_item',
            name='quantity',
        ),
    ]
